### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by developerpratika** [Laravel-Backpack/langfilemanager#30] opened 2017-02-07 07:29 UTC
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 17 updates, 0 removals
```
  - Updating backpack/backupmanager (1.1.11 => 1.1.15) Loading from cache

  [ErrorException]
  copy(D:\xampp\htdocs\backpackadmin\vendor/backpack/backupmanager/src\resour
  ces\views\backup.blade.php): failed to open stream: Permission denied

```

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

sir
i am  getting this issue when i run composer update

**Comment by OwenMelbz** [comment] 2017-02-07 07:59
Hi.

Try deleting the whole vendor folder then doing "composer update"

- as this is a support request and not a bug to do with Backpack and GitHub is only for package bugs, it will be better for you to ask for support on services like stackoverflow, or on the composer gitter chat.

As per the package guidelines I'll now close this, if anybody else wants to help you debug your issue they can, however I recommend going to stackoverflow for this.

**Closed as completed by OwenMelbz** 2017-02-07 07:59 UTC
